import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const soukouMincho = localFont({
  src: "./fonts/SoukouMincho.ttf",
  variable: "--font-soukou-mincho",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My-Blog",
  description: "Miyatarutyyy's Blog site generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} ${soukouMincho.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
