import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { Loading } from "@/src/components/Loading";
import { PageTransitionProvider } from "@/src/components/PageTransition";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const soukouMincho = localFont({
  src: "./fonts/SoukouMincho-subset.woff2",
  variable: "--font-soukou-mincho",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My-Blog",
  description: "Miyatarutyyy's Blog site generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} ${soukouMincho.variable}`}
    >
      <body>
        <Loading
          fonts={[
            {
              id: "system",
              kind: "system",
              label: "System fallback",
              fontFamily: "system-ui, sans-serif",
              sampleText: "A",
            },
            {
              id: "geist-sans",
              kind: "web",
              label: "Geist Sans",
              fontFamily: geistSans.style.fontFamily,
              sampleText: "A",
            },
            {
              id: "geist-mono",
              kind: "web",
              label: "Geist Mono",
              fontFamily: geistMono.style.fontFamily,
              sampleText: "A",
            },
            {
              id: "soukou-mincho",
              kind: "web",
              label: "SoukouMincho",
              fontFamily: soukouMincho.style.fontFamily,
              sampleText: "永",
            },
          ]}
        >
          <PageTransitionProvider>{children}</PageTransitionProvider>
        </Loading>
      </body>
    </html>
  );
}
